# dataset configs

dataset_cfg:
  dataset_type: Waymo
  data_root_dir: ../dataset/waymo/
  category_name: Vehicle
  # crop local area for tracking
  frame_npts: 1024
  frame_offset: 2.0
  frame_offset2: 0.0
  frame_scale: 1.0
  # crop the tracked target across frames to generate completion gt
  target_scale: 1.25
  target_offset: 0.0
  # params to simulate motion
  offset_max: [3., 10., 10.]
  up_axis: [0,-1,0]
  degree: True
  eval_cfg:
    cache: False
    use_z: True
    preload_offset: -1



# model configs

model_cfg:
  model_type: TrackAny
  train_memory_size: 2
  # ref_memory_size: 2
  eval_memory_size: 3
  backbone_cfg:
    RECONV:
      NAME: PointTransformer_DAPT
      trans_dim: 384
      depth: 12
      drop_path_rate: 0.1
      drop_rate: 0.
      cls_dim: 40
      num_heads: 6
      group_size: 32
      num_group: 128
      encoder_dims: 384
      rank: 72
      drop_adapter_rate: 0
      class_token: "None"
      prompt_token: "mean"
      patch_token: "None"



  rpn_cfg:
    feat_dim: 128
    n_smp_x: 3
    n_smp_y: 3
    n_smp_z: 5
    n_proposals: 64
    n_proposals_train: 64
    sample_method: shrink
    edge_aggr:
      pre_mlps: [129, 128, 128]
      mlps: [128, 128, 128]
      use_xyz: True
      nsample: 8
    # sigma_n2: 0.15
    # fixed_sigma_n2: True

# task configs
task_type: TrackAny
missing_threshold: 0.2

eval_cfg:
  batch_size: 1
  num_workers: 4
  iou_space: 3 
